name: Hello Test Build

on:
  push:
    branches:
      - main # Build only on pushes to main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Build
        uses: actions/checkout@v4

      - name: Init Cargo
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build
      - name: list dir
        run: ls

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/hello-rust.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
