name: Hello Test Build

on:
  push:
    tags:
      - "v*" # Trigger the workflow on a tag starting with 'v', e.g., v1.0.0
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Build
        uses: actions/checkout@v4

      - name: Init Cargo
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release
      - name: list dir
        run: ls target/release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
